export default () => ({
    'ability:frontal:static': 'Frontal (Static)',
    'ability:frontal:moving': 'Frontal',
    'ability:closest': 'Hit closest',
    'ability:heal:chunk': 'Heal',
    'ability:heal:over-time': 'HOT',
    'ability:buff': 'Buff',
    'ability:debuff': 'Debuff',
    'ability:debuff:reduc-heal': 'Debuff (Reduc heal)',
    'ability:dash': 'Dash',
    'ability:aoe:swirl': 'AOE (Swirl)',
    'ability:aoe:circle': 'AOE (Circle)',
    'ability:trap': 'Trap',
    'ability:fixate': 'Fixate',
    'ability:silence': 'Silence',
    'ability:spin': 'Spin',

    'cast:interruptible': 'Interruptible',
    'cast:non-interruptible': 'Non interruptible',
    'cast:instant': 'Instant',

    'do:dodge': 'Dodge',
    'do:run_away': 'Run away',
    'do:interrupt': 'Interrupt',
    'do:do_not_interrupt': 'Do not interrupt',
    'do:dispel': 'Dispel',
    'do:outheal': 'Outheal',
    'do:stun': 'Stun',
    'do:do_not_jump': 'Do not jump',
    'do:defensive': 'Use defensive',

    'target:self': 'Self',
    'target:all': 'All',
    'target:none': 'None',
    'target:random': 'Random',
    'target:tank': 'Tank',
    'target:healer': 'Healer',
    'target:dps': 'DPS',
    'target:melee': 'Melee',
    'target:ranged': 'Ranged',
    'target:enemy': 'Enemy',
    'target:ally': 'Ally',

    'dungeon:freehold': 'Freehold',
})